project:
  type: book

book:
  title: "Data science manual"
  author: "Jane Doe"
  date: "9/21/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
- part: "Getting Started"
  chapters: 
    - 'Entering the R ecosystem.qmd'
    - 'How R works.qmd'
    - 'How R programs.qmd'
    - 'Happy Git with R.qmd'
    - 'R and Data Science resources.qmd'
- part: "Data analysis workflow"
  chapters:
    - 'Designing an analytical activity.qmd'
    - 'Sampling.qmd'
    - 'Data cleaning and preparation.qmd'
    - 'Reproducibility.qmd'
    - 'Data exploration.qmd'
    - 'Data modeling.qmd'
    - 'Generating client deliverables.qmd'
- part: "Reporting"
  chapters:
    - 'Reports.qmd'
    - 'Presentations.qmd'
    - 'Dashboards.qmd'
- part: "Annexes"
  chapters: 
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

